# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('statecode', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='Alarmlevel',
            fields=[
                ('alarmlevel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'alarmlevel',
            },
        ),
        migrations.CreateModel(
            name='Censustract',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('countyfp', models.CharField(blank=True, max_length=3, null=True)),
                ('tractce', models.CharField(blank=True, max_length=6, null=True)),
                ('blkgrpce', models.CharField(blank=True, max_length=1, null=True)),
                ('geoid', models.CharField(blank=True, max_length=12, null=True)),
                ('namelsad', models.CharField(blank=True, max_length=13, null=True)),
                ('mtfcc', models.CharField(blank=True, max_length=5, null=True)),
                ('funcstat', models.CharField(blank=True, max_length=1, null=True)),
                ('aland', models.FloatField(blank=True, null=True)),
                ('awater', models.FloatField(blank=True, null=True)),
                ('intptlat', models.CharField(blank=True, max_length=11, null=True)),
                ('intptlon', models.CharField(blank=True, max_length=12, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'censustract',
            },
        ),
        migrations.CreateModel(
            name='Fireblock',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fma', models.CharField(blank=True, max_length=2, null=True)),
                ('resp_zone', models.CharField(blank=True, max_length=6, null=True)),
                ('jurisdict', models.CharField(blank=True, max_length=2, null=True)),
                ('dist_grp', models.CharField(blank=True, max_length=2, null=True)),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('of_fma', models.CharField(blank=True, max_length=26, null=True)),
                ('mv_label', models.CharField(blank=True, max_length=15, null=True)),
                ('shape_star', models.DecimalField(blank=True, decimal_places=65535, max_digits=65540, null=True)),
                ('shape_stle', models.DecimalField(blank=True, decimal_places=65535, max_digits=65540, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65540, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65540, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'fireblock',
            },
        ),
        migrations.CreateModel(
            name='Firestation',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('station', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(blank=True, max_length=38, null=True)),
                ('city', models.CharField(blank=True, max_length=28, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'firestation',
            },
        ),
        migrations.CreateModel(
            name='Fma',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fma', models.CharField(blank=True, max_length=26, null=True)),
                ('mv_label', models.CharField(blank=True, max_length=15, null=True)),
                ('shape_star', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_stle', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'fma',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('responderunit_id', models.IntegerField(blank=True, null=True)),
                ('runnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('alarmlevel_id', models.IntegerField(blank=True, null=True)),
                ('mutualaid_id', models.IntegerField(blank=True, null=True)),
                ('fmarespcomp', models.CharField(blank=True, max_length=6, null=True)),
                ('fireblock', models.CharField(blank=True, max_length=6, null=True)),
                ('neighborassoc', models.CharField(blank=True, max_length=18, null=True)),
                ('censustract', models.CharField(blank=True, max_length=6, null=True)),
                ('quad', models.CharField(blank=True, max_length=2, null=True)),
                ('streetname', models.CharField(blank=True, max_length=30, null=True)),
                ('streettype', models.CharField(blank=True, max_length=4, null=True)),
                ('quad2', models.CharField(blank=True, max_length=2, null=True)),
                ('streetname2', models.CharField(blank=True, max_length=30, null=True)),
                ('streettype2', models.CharField(blank=True, max_length=4, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=9, null=True)),
                ('incdate', models.DateField(blank=True, null=True)),
                ('typenaturecode_id', models.IntegerField(blank=True, null=True)),
                ('incsitfoundprm_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentsIncidents',
            fields=[
                ('incident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('runnumber', models.CharField(max_length=20)),
                ('fmarespcomp', models.CharField(max_length=6)),
                ('fireblock', models.CharField(max_length=6)),
                ('neighborassoc', models.CharField(max_length=18)),
                ('censustract', models.CharField(max_length=6)),
                ('quad', models.CharField(max_length=2)),
                ('streetname', models.CharField(max_length=30)),
                ('streettype', models.CharField(max_length=4)),
                ('quad2', models.CharField(max_length=2)),
                ('streetname2', models.CharField(max_length=30)),
                ('streettype2', models.CharField(max_length=4)),
                ('county', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=9)),
            ],
            options={
                'managed': False,
                'db_table': 'incidents_incidents',
            },
        ),
        migrations.CreateModel(
            name='Incsitfound',
            fields=[
                ('incsitfound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('incsitfoundsub_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('statecode', models.CharField(blank=True, max_length=3, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nfirs', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incsitfound',
            },
        ),
        migrations.CreateModel(
            name='Incsitfoundclass',
            fields=[
                ('incsitfoundclass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incsitfoundclass',
            },
        ),
        migrations.CreateModel(
            name='Incsitfoundsub',
            fields=[
                ('incsitfoundsub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('incsitfoundclass_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incsitfoundsub',
            },
        ),
        migrations.CreateModel(
            name='Inctimes',
            fields=[
                ('inctimes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timedesc_id', models.IntegerField()),
                ('incident_id', models.IntegerField()),
                ('responder_id', models.IntegerField(blank=True, null=True)),
                ('realtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'inctimes',
            },
        ),
        migrations.CreateModel(
            name='Mutualaid',
            fields=[
                ('mutualaid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nfirs', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'mutualaid',
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.IntegerField()),
                ('responder_id', models.IntegerField()),
                ('responderunit_id', models.IntegerField(blank=True, null=True)),
                ('codetosc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'responder',
            },
        ),
        migrations.CreateModel(
            name='Responderunit',
            fields=[
                ('responderunit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=6, null=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('translateto', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_id', models.IntegerField(blank=True, null=True)),
                ('process', models.IntegerField(blank=True, null=True)),
                ('versaterm', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'responderunit',
            },
        ),
        migrations.CreateModel(
            name='Situationfound',
            fields=[
                ('situationfound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nemsis', models.CharField(blank=True, max_length=10, null=True)),
                ('e09_15', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'situationfound',
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'spatial_ref_sys',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Timedesc',
            fields=[
                ('timedesc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'timedesc',
            },
        ),
        migrations.CreateModel(
            name='Typenaturecode',
            fields=[
                ('typenaturecode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=8, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('nemsis', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'typenaturecode',
            },
        ),
    ]
