# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170124_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fireblock',
            options={'managed': False},
        ),
    ]
